name: Submit to WinGet

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  winget:
    runs-on: ubuntu-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@7bd472be23763def6e16bd06cc8b1cdfab0e2fd5 # main
        with:
          identifier: goptics.vizb
          installers-regex: '\.zip$'
          token: ${{ secrets.WINGET_TOKEN }}
